language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install: 
  - echo "nothing need to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no test"

script:
  - docker --version
  - docker build -t simple-node .
  - docker tag simple-node beersheep/simple-node:latest

# Tasks to performed after_success
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push beersheep/simple-node
